fragment PagesParts on Pages {
  blocks {
    __typename
    ... on PagesBlocksNavigation {
      alignment
      menuItems {
        __typename
        label
        link
        subMenuItems {
          __typename
          label
          link
        }
      }
      rightMenuItems {
        __typename
        label
        link
        variant
      }
    }
    ... on PagesBlocksHeroV1 {
      title
      description
      form {
        __typename
        placeholder
        button {
          __typename
          label
          link
          variant
        }
      }
      background
    }
    ... on PagesBlocksHeroV2 {
      title
      description
      background
      button {
        __typename
        label
        link
      }
    }
    ... on PagesBlocksHeroV3 {
      title
      description
      background
      actionButtons {
        __typename
        label
        link
        variant
      }
    }
    ... on PagesBlocksFeaturesV1 {
      title
      subtitle
      description
      features {
        __typename
        imageIcon
        title
        description
      }
    }
    ... on PagesBlocksFeaturesV2 {
      title
      description
      features {
        __typename
        title
        description
      }
    }
    ... on PagesBlocksFeaturesV3 {
      features {
        __typename
        imageIcon
        title
        description
      }
    }
    ... on PagesBlocksProjects {
      projectItem {
        __typename
        link
        image
      }
    }
    ... on PagesBlocksVision {
      title
      description
    }
    ... on PagesBlocksValues {
      title
      valueItems {
        __typename
        image
        description
      }
    }
    ... on PagesBlocksFooter {
      menuItems {
        __typename
        label
        link
      }
    }
  }
}
